-- Sahayak AI server-owned account schema.
-- Apply with a database administrator connection or the Supabase SQL editor.
-- The React browser must not receive database credentials or query these
-- tables directly; FastAPI owns OTP verification, JWT sessions and access.

create table if not exists public.sahayak_accounts (
  id bigint generated by default as identity primary key,
  phone_number varchar(20) not null unique,
  full_name varchar(120),
  state varchar(100),
  district varchar(120),
  village_or_town varchar(120),
  address text,
  user_type varchar(48) check (
    user_type is null or user_type in (
      'cooperative_member',
      'farmer',
      'pacs_member',
      'cooperative_official',
      'rural_stakeholder',
      'other'
    )
  ),
  cooperative_role varchar(120),
  profile_completed boolean not null default false,
  is_active boolean not null default true,
  token_version integer not null default 1 check (token_version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sahayak_otp_codes (
  id bigint generated by default as identity primary key,
  phone_number varchar(20) not null,
  code_hash varchar(255) not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  created_at timestamptz not null default now()
);

create index if not exists sahayak_otp_codes_active_lookup_idx
  on public.sahayak_otp_codes (phone_number, id desc)
  where used_at is null;

create or replace function public.sahayak_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sahayak_accounts_touch_updated_at on public.sahayak_accounts;
create trigger sahayak_accounts_touch_updated_at
before update on public.sahayak_accounts
for each row execute function public.sahayak_touch_updated_at();

-- Explicitly deny the Supabase browser roles. FastAPI connects with the
-- server database credential and is the only account-data access boundary.
revoke all on table public.sahayak_accounts from anon, authenticated;
revoke all on table public.sahayak_otp_codes from anon, authenticated;
revoke all on sequence public.sahayak_accounts_id_seq from anon, authenticated;
revoke all on sequence public.sahayak_otp_codes_id_seq from anon, authenticated;
