-- Sahayak grievance assistance records. The FastAPI backend is the only
-- access boundary; CPGRAMS remains the official system of record.

create table if not exists public.sahayak_grievances (
  id varchar(40) primary key,
  account_id bigint not null references public.sahayak_accounts(id) on delete restrict,
  status varchar(32) not null check (status in (
    'DRAFT', 'READY_FOR_CONFIRMATION', 'USER_CONFIRMED', 'SUBMITTING',
    'SUBMITTED', 'ACKNOWLEDGED', 'UNDER_PROCESS', 'ACTION_REQUIRED',
    'RESOLVED', 'CLOSED', 'ESCALATED', 'APPEAL_AVAILABLE',
    'APPEAL_SUBMITTED', 'SUBMISSION_FAILED', 'UNKNOWN'
  )),
  category varchar(48) not null check (category in (
    'PACS_ISSUE', 'COOPERATIVE_SOCIETY', 'PAYMENT', 'LOAN',
    'INSURANCE_CLAIM', 'GOVERNMENT_SCHEME', 'AGRICULTURE_SERVICE',
    'FINANCIAL_SERVICE', 'DOCUMENT_CERTIFICATE', 'ADMINISTRATIVE',
    'OTHER_GOVERNMENT'
  )),
  subject varchar(180),
  description text,
  original_language varchar(16),
  organization varchar(180),
  state varchar(100),
  district varchar(120),
  locality varchar(120),
  incident_date date,
  amount_description varchar(80),
  has_contacted_organization boolean,
  prior_reference varchar(120),
  authority_key varchar(64),
  authority_name varchar(180),
  destination_name varchar(180),
  destination_url varchar(500),
  official_tracking_url varchar(500),
  routing_reason text,
  routed_at timestamptz,
  submission_method varchar(32),
  official_reference varchar(160),
  official_reference_source varchar(32),
  confirmed_at timestamptz,
  handoff_opened_at timestamptz,
  submitted_at timestamptz,
  acknowledged_at timestamptz,
  last_status_checked_at timestamptz,
  status_changed_at timestamptz not null,
  resolved_at timestamptz,
  closed_at timestamptz,
  escalated_at timestamptz,
  appeal_submitted_at timestamptz,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sahayak_grievances_account_updated_idx
  on public.sahayak_grievances (account_id, updated_at desc);
create index if not exists sahayak_grievances_account_status_idx
  on public.sahayak_grievances (account_id, status);

create table if not exists public.sahayak_grievance_events (
  id bigint generated by default as identity primary key,
  grievance_id varchar(40) not null references public.sahayak_grievances(id) on delete restrict,
  event_type varchar(48) not null,
  from_status varchar(32),
  to_status varchar(32),
  actor varchar(24) not null check (actor in ('MEMBER', 'SYSTEM', 'ADMIN', 'OFFICIAL_SYNC')),
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists sahayak_grievance_events_grievance_time_idx
  on public.sahayak_grievance_events (grievance_id, created_at, id);

drop trigger if exists sahayak_grievances_touch_updated_at on public.sahayak_grievances;
create trigger sahayak_grievances_touch_updated_at
before update on public.sahayak_grievances
for each row execute function public.sahayak_touch_updated_at();

revoke all on table public.sahayak_grievances from anon, authenticated;
revoke all on table public.sahayak_grievance_events from anon, authenticated;
revoke all on sequence public.sahayak_grievance_events_id_seq from anon, authenticated;
