-- Device biometric sign-in for Sahayak AI.
-- WebAuthn passkeys keep biometric templates and private keys on the user's
-- device. This schema deliberately stores only public credential material.

alter table public.sahayak_accounts
  add column if not exists face_id_enabled boolean not null default false,
  add column if not exists last_mobile_verification_at timestamptz;

create table if not exists public.sahayak_webauthn_credentials (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.sahayak_accounts(id) on delete cascade,
  credential_id varchar(1024) not null unique,
  credential_public_key text not null,
  sign_count integer not null default 0 check (sign_count >= 0),
  transports varchar(128),
  device_type varchar(32),
  backed_up boolean not null default false,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);

create index if not exists sahayak_webauthn_credentials_account_idx
  on public.sahayak_webauthn_credentials (account_id);

create table if not exists public.sahayak_webauthn_ceremonies (
  id varchar(96) primary key,
  account_id bigint references public.sahayak_accounts(id) on delete cascade,
  purpose varchar(24) not null check (purpose in ('registration', 'authentication')),
  challenge varchar(128) not null,
  rp_id varchar(253) not null,
  origin varchar(255) not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists sahayak_webauthn_ceremonies_expiry_idx
  on public.sahayak_webauthn_ceremonies (expires_at);

-- The FastAPI service is the only owner of account and credential data.
revoke all on table public.sahayak_webauthn_credentials from anon, authenticated;
revoke all on table public.sahayak_webauthn_ceremonies from anon, authenticated;
revoke all on sequence public.sahayak_webauthn_credentials_id_seq from anon, authenticated;
